# globals.py

EYE_AR_THRESH = 0.25
EYE_AR_CONSEC_FRAMES = 2
MAR_THRESH = 0.75
MOUTH_AR_CONSEC_FRAMES = 3
HAR_THRESH = 0.5
NOD_AR_CONSEC_FRAMES = 3
COUNTER = 0
TOTAL = 0
mCOUNTER = 0
mTOTAL = 0
hCOUNTER = 0
hTOTAL = 0
